import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Pokemons</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favic.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Pokemon in Next</h1>
        <h2 className={styles.descriptiom}>
          Aqui empieza la aventurilla de jugar con los pokemons en Next
        </h2>
        <p className={styles.descriptiom}>Yupiiiiii!!</p>
        <p className={styles.descriptiom}>
          En este challenge vamos a ver que queda de esa semana 3 y de la api de
          Pokemon
        </p>
      </main>

      <footer className={styles.footer}>
        <p>by Silvia</p>
      </footer>
    </div>
  );
}
